global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8080']
    metrics_path: /metrics
  - job_name: 'reporter'
    static_configs:
      - targets: ['reporter:8090']
    metrics_path: /metrics
  - job_name: 'ti-enrichment'
    static_configs:
      - targets: ['ti:8070']
    metrics_path: /metrics
